[tool.isort]
line_length = 80
atomic = true
include_trailing_comma = true
use_parentheses = true
profile = "black"
lines_after_imports = 2
combine_as_imports = true
multi_line_output = 3

[tool.black]
line-length = 80
target-version = ['py312']

