# Form implementation generated from reading ui file 'schema_manager.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_SchemaManager(object):
    def setupUi(self, SchemaManager):
        SchemaManager.setObjectName("SchemaManager")
        SchemaManager.resize(800, 400)
        SchemaManager.setMinimumSize(QtCore.QSize(800, 400))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            SchemaManager.sizePolicy().hasHeightForWidth()
        )
        SchemaManager.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SchemaManager)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=SchemaManager)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.schema_name_input = QtWidgets.QLineEdit(parent=SchemaManager)
        self.schema_name_input.setObjectName("schema_name_input")
        self.verticalLayout_2.addWidget(self.schema_name_input)
        self.label_3 = QtWidgets.QLabel(parent=SchemaManager)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.scrollArea = QtWidgets.QScrollArea(parent=SchemaManager)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 408, 333))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.property_container = QtWidgets.QVBoxLayout()
        self.property_container.setObjectName("property_container")

        self.frame = QtWidgets.QFrame()
        self.frame.setLayout(self.property_container)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.property_container.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.frame)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.add_property_btn = QtWidgets.QPushButton(parent=SchemaManager)
        self.add_property_btn.setObjectName("add_property_btn")
        self.verticalLayout_2.addWidget(self.add_property_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=SchemaManager)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.schemas_list = QtWidgets.QListWidget(parent=SchemaManager)
        self.schemas_list.setObjectName("schemas_list")
        self.verticalLayout.addWidget(self.schemas_list)
        self.add_schema_btn = QtWidgets.QPushButton(parent=SchemaManager)
        self.add_schema_btn.setObjectName("add_schema_btn")
        self.verticalLayout.addWidget(self.add_schema_btn)
        self.delete_schema_btn = QtWidgets.QPushButton(parent=SchemaManager)
        self.delete_schema_btn.setObjectName("delete_schema_btn")
        self.verticalLayout.addWidget(self.delete_schema_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label.setBuddy(self.schema_name_input)
        self.label_2.setBuddy(self.schemas_list)

        self.retranslateUi(SchemaManager)
        QtCore.QMetaObject.connectSlotsByName(SchemaManager)

    def retranslateUi(self, SchemaManager):
        _translate = QtCore.QCoreApplication.translate
        SchemaManager.setWindowTitle(
            _translate("SchemaManager", "PyQT Schema Manager")
        )
        self.label.setText(_translate("SchemaManager", "Schema Name"))
        self.schema_name_input.setPlaceholderText(
            _translate("SchemaManager", "e.g. User")
        )
        self.label_3.setText(_translate("SchemaManager", "Property Fields"))
        self.add_property_btn.setText(
            _translate("SchemaManager", "Add Property Field")
        )
        self.label_2.setText(_translate("SchemaManager", "Available Schemas"))
        self.add_schema_btn.setText(_translate("SchemaManager", "Add Schema"))
        self.delete_schema_btn.setText(
            _translate("SchemaManager", "Delete Schema")
        )
